apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-worker
  labels:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-worker
  template:
    metadata:
      labels:
        app: python-worker
    spec:
      containers:
      - name: python-worker
        image: registry.gitlab.com/teedeemicro/python-worker:0.0.2
        imagePullPolicy: Always
        #ports:
        # - containerPort: 5001
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
